# This is a basic workflow to help you get started with Actions

name: CI
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
  AWS_REGION: "eu-central-1"

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}

      - name: Init terraform
        run: terraform init

      - name: Terraform apply
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          shell: bash
          command: terraform apply -auto-approve

#      - name: Terraform destroy
#        uses: nick-fields/retry@v2
#        with:
#          timeout_minutes: 60
#          max_attempts: 3
#          shell: bash
#          command: terraform destroy -auto-approve


